server:
  port: 9000

spring:
  application:
    name: project
  datasource:
    url: jdbc:postgresql://localhost:5435/project
    username: 'postgres'
    password: 'password'

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: 'true'
    properties:
      show-sql: 'true'


